from __future__ import annotations

import hashlib
from typing import Any

from faster_raster.adapter_contract import stable_json

THEME_REGISTRY_VERSION = "1.0.0-alpha.2"

THEMES: dict[str, dict[str, Any]] = {
    "optical_imagery": {"theme_id": "optical_imagery", "render_role": "primary_imagery", "visual_priority": 0, "default_z_order": 0, "default_opacity": 1.0, "minimum_opacity": 0.80, "maximum_opacity": 1.0, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "natural_color", "nodata_render_policy": "transparent", "legend_priority": 0, "real_raster_pixels_required": True, "may_be_primary": True, "diagnostic_only": False},
    "radar_imagery": {"theme_id": "radar_imagery", "render_role": "imagery_alternative", "visual_priority": 1, "default_z_order": 5, "default_opacity": 0.85, "minimum_opacity": 0.60, "maximum_opacity": 1.0, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "radar_db_grayscale", "nodata_render_policy": "transparent", "legend_priority": 1, "real_raster_pixels_required": True, "may_be_primary": True, "diagnostic_only": False},
    "aerial_imagery": {"theme_id": "aerial_imagery", "render_role": "primary_imagery", "visual_priority": 0, "default_z_order": 0, "default_opacity": 1.0, "minimum_opacity": 0.80, "maximum_opacity": 1.0, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "natural_color", "nodata_render_policy": "transparent", "legend_priority": 0, "real_raster_pixels_required": True, "may_be_primary": True, "diagnostic_only": False},
    "elevation": {"theme_id": "elevation", "render_role": "terrain_context", "visual_priority": 2, "default_z_order": 10, "default_opacity": 0.20, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "luminosity", "default_resampling": "bilinear", "default_color_policy": "grayscale", "nodata_render_policy": "transparent", "legend_priority": 3, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "hillshade": {"theme_id": "hillshade", "render_role": "terrain_context", "visual_priority": 2, "default_z_order": 10, "default_opacity": 0.18, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "multiply", "default_resampling": "bilinear", "default_color_policy": "grayscale", "nodata_render_policy": "transparent", "legend_priority": 3, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "terrain": {"theme_id": "terrain", "render_role": "terrain_context", "visual_priority": 2, "default_z_order": 10, "default_opacity": 0.22, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "multiply", "default_resampling": "bilinear", "default_color_policy": "terrain_tint", "nodata_render_policy": "transparent", "legend_priority": 3, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "landcover_categorical": {"theme_id": "landcover_categorical", "render_role": "thematic_overlay", "visual_priority": 3, "default_z_order": 20, "default_opacity": 0.30, "minimum_opacity": 0.20, "maximum_opacity": 0.40, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "categorical_palette", "nodata_render_policy": "transparent", "legend_priority": 4, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "landcover_continuous": {"theme_id": "landcover_continuous", "render_role": "thematic_overlay", "visual_priority": 3, "default_z_order": 20, "default_opacity": 0.25, "minimum_opacity": 0.10, "maximum_opacity": 0.35, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "continuous_ramp", "nodata_render_policy": "transparent", "legend_priority": 4, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "climate_continuous": {"theme_id": "climate_continuous", "render_role": "environmental_context", "visual_priority": 4, "default_z_order": 30, "default_opacity": 0.18, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "multiply", "default_resampling": "bilinear", "default_color_policy": "continuous_ramp", "nodata_render_policy": "transparent", "legend_priority": 5, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "hydrology": {"theme_id": "hydrology", "render_role": "environmental_context", "visual_priority": 4, "default_z_order": 30, "default_opacity": 0.22, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "water_ramp", "nodata_render_policy": "transparent", "legend_priority": 5, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "vegetation_index": {"theme_id": "vegetation_index", "render_role": "environmental_context", "visual_priority": 4, "default_z_order": 30, "default_opacity": 0.22, "minimum_opacity": 0.10, "maximum_opacity": 0.30, "default_blend_mode": "multiply", "default_resampling": "bilinear", "default_color_policy": "vegetation_ramp", "nodata_render_policy": "transparent", "legend_priority": 5, "real_raster_pixels_required": True, "may_be_primary": False, "diagnostic_only": False},
    "quality_mask": {"theme_id": "quality_mask", "render_role": "diagnostic_overlay", "visual_priority": 5, "default_z_order": 40, "default_opacity": 0.15, "minimum_opacity": 0.05, "maximum_opacity": 0.20, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "mask", "nodata_render_policy": "transparent", "legend_priority": 6, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": True},
    "cloud_mask": {"theme_id": "cloud_mask", "render_role": "diagnostic_overlay", "visual_priority": 5, "default_z_order": 40, "default_opacity": 0.15, "minimum_opacity": 0.05, "maximum_opacity": 0.20, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "cloud_mask", "nodata_render_policy": "transparent", "legend_priority": 6, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": True},
    "uncertainty": {"theme_id": "uncertainty", "render_role": "diagnostic_overlay", "visual_priority": 5, "default_z_order": 40, "default_opacity": 0.12, "minimum_opacity": 0.05, "maximum_opacity": 0.20, "default_blend_mode": "normal", "default_resampling": "bilinear", "default_color_policy": "uncertainty", "nodata_render_policy": "transparent", "legend_priority": 6, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": True},
    "boundary": {"theme_id": "boundary", "render_role": "annotation", "visual_priority": 6, "default_z_order": 50, "default_opacity": 1.0, "minimum_opacity": 0.70, "maximum_opacity": 1.0, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "line", "nodata_render_policy": "transparent", "legend_priority": 7, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": False},
    "annotation": {"theme_id": "annotation", "render_role": "annotation", "visual_priority": 6, "default_z_order": 50, "default_opacity": 1.0, "minimum_opacity": 0.70, "maximum_opacity": 1.0, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "label", "nodata_render_policy": "transparent", "legend_priority": 7, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": False},
    "semantic_fallback": {"theme_id": "semantic_fallback", "render_role": "fallback", "visual_priority": 7, "default_z_order": 60, "default_opacity": 0.10, "minimum_opacity": 0.05, "maximum_opacity": 0.15, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "hatched_fallback", "nodata_render_policy": "transparent", "legend_priority": 8, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": True},
    "unavailable_source": {"theme_id": "unavailable_source", "render_role": "unavailable", "visual_priority": 8, "default_z_order": 70, "default_opacity": 0.08, "minimum_opacity": 0.02, "maximum_opacity": 0.12, "default_blend_mode": "normal", "default_resampling": "nearest", "default_color_policy": "unavailable_hatch", "nodata_render_policy": "transparent", "legend_priority": 9, "real_raster_pixels_required": False, "may_be_primary": False, "diagnostic_only": True},
}


def theme_registry() -> dict[str, Any]:
    registry = {"schema_version": 1, "theme_registry_version": THEME_REGISTRY_VERSION, "themes": [THEMES[key] for key in sorted(THEMES)]}
    registry["preview_theme_registry_sha256"] = hashlib.sha256(stable_json(registry).encode("utf-8")).hexdigest()
    return registry


def get_theme(theme_id: str) -> dict[str, Any]:
    if theme_id not in THEMES:
        raise KeyError(f"unknown preview theme: {theme_id}")
    return THEMES[theme_id]


def sort_layers_by_theme(layers: list[dict[str, Any]]) -> list[dict[str, Any]]:
    return sorted(layers, key=lambda layer: (get_theme(layer["theme"])["visual_priority"], get_theme(layer["theme"])["default_z_order"], layer.get("source_id", "")))
