from __future__ import annotations

import hashlib
from typing import Any
from faster_raster.adapter_contract import stable_json

CAPABILITY_NAMES = ["discover", "resolve", "bounded_probe", "preview_window", "preview_tile", "materialize", "metadata", "authentication", "redirect_support", "range_request_support", "spatial_subset_support", "temporal_subset_support"]

ADAPTERS: list[dict[str, Any]] = [
    {"adapter_id": "arcgis_imageserver_preview", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["aerial_imagery", "categorical_landcover", "elevation_hillshade"], "supported_media_types": ["image/png", "image/jpeg"], "supported_asset_roles": ["preview", "natural_color", "categorical_overlay", "hillshade"], "credential_requirement": "none", "allowed_hosts": ["imagery.nationalmap.gov", "pdi.scinet.usda.gov", "elevation.nationalmap.gov"], "redirect_hosts": ["imagery.nationalmap.gov", "pdi.scinet.usda.gov", "elevation.nationalmap.gov"], "maximum_redirects": 2, "bounded_request_behavior": "single exportImage request with width, height, and byte caps", "deterministic_resolution_behavior": "query parameters sorted; AOI and size from render contract", "failure_taxonomy": ["host_not_allowed", "unsupported_media_type", "preview_byte_cap_exceeded", "preview_dimension_cap_exceeded", "preview_render_failed"], "capabilities": {"discover": True, "resolve": True, "bounded_probe": True, "preview_window": True, "preview_tile": False, "materialize": False, "metadata": True, "authentication": False, "redirect_support": True, "range_request_support": False, "spatial_subset_support": True, "temporal_subset_support": True}},
    {"adapter_id": "stac_api", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["optical_satellite_imagery", "radar_imagery"], "supported_media_types": ["application/geo+json", "image/tiff", "image/tiff; application=geotiff"], "supported_asset_roles": ["data", "red", "green", "blue", "nir", "vv", "vh"], "credential_requirement": "source_specific", "allowed_hosts": ["planetarycomputer.microsoft.com", "sentinel2l2a01.blob.core.windows.net", "catalogue.dataspace.copernicus.eu"], "redirect_hosts": ["planetarycomputer.microsoft.com", "sentinel2l2a01.blob.core.windows.net", "catalogue.dataspace.copernicus.eu"], "maximum_redirects": 2, "bounded_request_behavior": "bounded search and deterministic asset selection; no full materialization in alpha.2", "deterministic_resolution_behavior": "sort by score then item id then asset key", "failure_taxonomy": ["stac_search_failed", "stac_item_not_found", "stac_asset_not_found", "unsupported_asset_role", "credentials_required"], "capabilities": {"discover": True, "resolve": True, "bounded_probe": True, "preview_window": False, "preview_tile": False, "materialize": False, "metadata": True, "authentication": True, "redirect_support": True, "range_request_support": False, "spatial_subset_support": True, "temporal_subset_support": True}},
    {"adapter_id": "http_cog_geotiff_preview", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["optical_satellite_imagery", "climate_environmental_context"], "supported_media_types": ["image/tiff", "image/tiff; application=geotiff"], "supported_asset_roles": ["preview", "derived_geotiff"], "credential_requirement": "source_specific", "allowed_hosts": [], "redirect_hosts": [], "maximum_redirects": 2, "bounded_request_behavior": "range probe and bounded preview only when host allowlisted", "deterministic_resolution_behavior": "window from render contract; no arbitrary URL fetching", "failure_taxonomy": ["host_not_allowed", "unsupported_media_type", "preview_byte_cap_exceeded"], "capabilities": {"discover": False, "resolve": True, "bounded_probe": True, "preview_window": True, "preview_tile": False, "materialize": False, "metadata": True, "authentication": True, "redirect_support": True, "range_request_support": True, "spatial_subset_support": True, "temporal_subset_support": False}},
    {"adapter_id": "ogc_wms_preview", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["terrain", "landcover", "environmental_context"], "supported_media_types": ["image/png", "image/jpeg"], "supported_asset_roles": ["preview"], "credential_requirement": "source_specific", "allowed_hosts": [], "redirect_hosts": [], "maximum_redirects": 2, "bounded_request_behavior": "GetCapabilities and GetMap only with allowlisted layer/style/CRS and dimensions", "deterministic_resolution_behavior": "tile order and GetMap parameters sorted from contract", "failure_taxonomy": ["host_not_allowed", "unsupported_media_type", "preview_dimension_cap_exceeded"], "capabilities": {"discover": True, "resolve": True, "bounded_probe": True, "preview_window": True, "preview_tile": False, "materialize": False, "metadata": True, "authentication": True, "redirect_support": True, "range_request_support": False, "spatial_subset_support": True, "temporal_subset_support": True}},
    {"adapter_id": "ogc_wmts_preview", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["imagery", "terrain", "landcover"], "supported_media_types": ["image/png", "image/jpeg"], "supported_asset_roles": ["preview_tile"], "credential_requirement": "source_specific", "allowed_hosts": [], "redirect_hosts": [], "maximum_redirects": 2, "bounded_request_behavior": "bounded tile count with deterministic matrix selection", "deterministic_resolution_behavior": "tile ordering by matrix, row, column", "failure_taxonomy": ["preview_tile_cap_exceeded", "host_not_allowed", "unsupported_media_type"], "capabilities": {"discover": True, "resolve": True, "bounded_probe": True, "preview_window": False, "preview_tile": True, "materialize": False, "metadata": True, "authentication": True, "redirect_support": True, "range_request_support": False, "spatial_subset_support": True, "temporal_subset_support": True}},
    {"adapter_id": "static_verified_artifact", "adapter_version": "1.0.0-alpha.2", "supported_source_categories": ["climate_environmental_context"], "supported_media_types": ["image/tiff"], "supported_asset_roles": ["derived_geotiff"], "credential_requirement": "none", "allowed_hosts": [], "redirect_hosts": [], "maximum_redirects": 0, "bounded_request_behavior": "offline verified artifact only", "deterministic_resolution_behavior": "content-addressed alpha.1 artifact and metadata contract", "failure_taxonomy": ["source_not_allowlisted", "preview_render_failed"], "capabilities": {"discover": False, "resolve": True, "bounded_probe": False, "preview_window": True, "preview_tile": False, "materialize": False, "metadata": True, "authentication": False, "redirect_support": False, "range_request_support": False, "spatial_subset_support": False, "temporal_subset_support": False}},
]

def capability_hash(capability: dict[str, Any]) -> str:
    payload = {k: v for k, v in capability.items() if k != "adapter_capability_contract_sha256"}
    return hashlib.sha256(stable_json(payload).encode("utf-8")).hexdigest()

def adapter_capabilities() -> list[dict[str, Any]]:
    out = []
    for item in ADAPTERS:
        adapter = dict(item)
        adapter["capabilities"] = dict(item["capabilities"])
        adapter["adapter_capability_contract_sha256"] = capability_hash(adapter)
        out.append(adapter)
    return out

def adapter_capability_catalog() -> dict[str, Any]:
    adapters = sorted(adapter_capabilities(), key=lambda item: item["adapter_id"])
    payload = {"schema_version": 1, "adapter_count": len(adapters), "adapters": adapters}
    payload["adapter_capability_catalog_sha256"] = hashlib.sha256(stable_json(payload).encode("utf-8")).hexdigest()
    return payload
